name: Main Workflow

on:
  push:
    branches:
      - flow_test

jobs:

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Add steps to run your tests here

  run-pyinstaller-matrix:
    strategy:
      # super important if you want to see all results, even if one fails
      # fail-fast is true by default
      fail-fast: true
      matrix:
          os: [ubuntu-latest, windows-latest, macOS-latest]
          spec_file: [FMD3-API.spec, FMD3-Client.spec, FMD3-WebClient.spec]
    needs: run_tests
    uses: ./.github/workflows/pyinstaller.yaml
    with:
        os: ${{ matrix.os }}
        spec_file: ${{ matrix.spec_file }}

