name: Main Workflow

on:
  push:
    branches:
      - flow_test
env:
    IMAGE_NAME: "thepromidius/fmd3-api"

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run the tests
        run: |
          python -m unittest discover -s tests/*


  run-pyinstaller-matrix:
    strategy:
      # super important if you want to see all results, even if one fails
      # fail-fast is true by default
      fail-fast: false
      matrix:
          os: [ubuntu-latest, windows-latest, macOS-latest]
#          os: [windows-latest]
    needs: run_tests
    uses: ./.github/workflows/os_pyinstaller.yaml
    with:
        os: ${{ matrix.os }}

  docker:
    name: Test and Build - Nightly Version
    needs: [ run_tests ]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/flow_test' }}
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:flow_test