name: PyInstaller Workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        default: 'ubuntu-latest'
        type: string

jobs:
  build:
    strategy:
        fail-fast: false
        matrix:
          spec_file: ${{ contains(steps.detect_bump.outputs.bumped_packages, 'FMD3_API') && ['FMD3-API_SingleExe'] ||
            contains(steps.detect_bump.outputs.bumped_packages, 'FMD3_Tkinter') && ['FMD3-Client_SingleExe', 'FMD3-WebClient_SingleExe'] ||
            [] }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Executable
        uses: ./.github/workflows/app_pyinstaller
        with:
          spec_file: ${{ matrix.spec_file }}
          os: ${{ inputs.os }}
