name: PyInstaller Workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        default: 'ubuntu-latest'
        type: string

jobs:
  build:
    strategy:
        matrix:
            spec_file: [FMD3-API.spec, FMD3-Client.spec, FMD3-WebClient.spec]
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip PyInstaller
          pip install -r requirements.txt
      - name: Build Executable
        uses: ./.github/workflows/app_pyinstaller
        with:
          spec_file: ${{ matrix.spec_file }}
