name: PyInstaller Workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        default: 'ubuntu-latest'
        type: string
      spec_file:
        required: true
        description: 'The .spec file to build'
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip PyInstaller
          pip install -r requirements.txt
      - name: Build Executable
        run: |
          echo "Building ${{ inputs.spec_file }}..."
          PyInstaller pyinstaller/${{ inputs.spec_file }}
