name: PyInstaller Workflow
on:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed

jobs:
  build_windows:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          spec_file:
            - FMD3-API.spec
            # Add more .spec files as needed
      steps:
        -
          name: Checkout repository
          uses: actions/checkout@v3
        -
          name: Set up Python 3.11
          uses: actions/setup-python@v4
          with:
            python-version: 3.11
            cache: 'pip'
        -
          name: Install dependencies
          run: |
            python -m pip install --upgrade pip PyInstaller
            pip install -r requirements.txt
        -
          name: Build Windows Executable
          run: |
            for spec_file in ${{ matrix.spec_file }}; do
              echo "Building $spec_file..."
              PyInstaller pyinstaller/$spec_file
            done
